# Configuration Settings for ZED-F9P device
# Moving base receiver
# ! UART1 output is connected to rover UART2 for moving base RTCM message

debug: 1                 # Range 0-4 (0 means no debug statements will print)

# device: /dev/ttyUSB1
device: /dev/ttymod_rtk2blite
frame_id: gps0

uart1:
  # baudrate: 460800
  baudrate: 921600
  in: 35    # Input UBX, NMEA, and RTCM3
  out: 1    # Output UBX


# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: false
    posecef: false
